version: 2

models:
  - name: fact_student_activity
    description: Daily student activity metrics aggregated from events
    columns:
      - name: activity_key
        description: Surrogate key for student + date
        tests:
          - unique
          - not_null
      
      - name: student_id
        description: Student identifier
        tests:
          - not_null
          - relationships:
              to: ref('dim_student')
              field: student_id
      
      - name: activity_date
        description: Date of activity
        tests:
          - not_null
      
      - name: total_events
        description: Total events for this student on this day
        tests:
          - not_null
      
      - name: accuracy_rate
        description: Accuracy rate for problem attempts
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
              inclusive: true

  - name: fact_learning_progress
    description: Student learning progress by unit with mastery tracking
    columns:
      - name: progress_key
        description: Surrogate key for student + unit + date
        tests:
          - unique
          - not_null
      
      - name: student_id
        description: Student identifier
        tests:
          - not_null
      
      - name: learning_unit_id
        description: Learning unit identifier
        tests:
          - not_null
          - relationships:
              to: ref('dim_learning_unit')
              field: learning_unit_id
      
      - name: mastery_status
        description: Current mastery status
        tests:
          - accepted_values:
              values: ['mastered', 'in_progress', 'not_started']
      
      - name: accuracy_rate
        description: Accuracy rate for this unit
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
              inclusive: true

  - name: fact_product_events
    description: "Event-level fact table for ELA and Science product interactions"
    
    columns:
      - name: event_key
        description: "Surrogate key for this event"
        tests:
          - unique
          - not_null
      
      - name: event_id
        description: "Natural key from source system"
        tests:
          - unique
          - not_null
      
      - name: user_key
        description: "Foreign key to dim_user"
        tests:
          - not_null
          - relationships:
              to: ref('dim_user')
              field: user_key
      
      - name: product_key
        description: "Foreign key to dim_product"
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_key
      
      - name: verb_key
        description: "Foreign key to dim_verb"
        tests:
          - not_null
          - relationships:
              to: ref('dim_verb')
              field: verb_key
      
      - name: object_key
        description: "Foreign key to dim_object"
        tests:
          - not_null
          - relationships:
              to: ref('dim_object')
              field: object_key
      
      - name: date_key
        description: "Foreign key to dim_date"
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
      
      - name: event_timestamp
        description: "Timestamp when event occurred"
        tests:
          - not_null