name: 'amplify_analytics'
version: '1.0.0'
config-version: 2

profile: 'amplify_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  amplify_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
    core:
      dimensions:
        +materialized: table
        +schema: analytics
      facts:
        +materialized: incremental
        +schema: analytics
        +on_schema_change: "fail"