version: 2

models:
  - name: mart_student_progress
    description: |
      Comprehensive student progress mart combining activity, learning progress, and dimensional context.
      One row per student with all metrics for engagement, mastery, and demographic analysis.
    columns:
      - name: student_id
        description: Unique student identifier
        tests:
          - unique
          - not_null
      
      - name: full_name
        description: Student full name
        tests:
          - not_null
      
      - name: school_id
        description: Current school
        tests:
          - not_null
      
      - name: engagement_level
        description: Engagement classification based on recent activity
        tests:
          - accepted_values:
              values: ['highly_engaged', 'moderately_engaged', 'low_engagement', 'inactive']
      
      - name: progress_status
        description: Progress classification based on mastery rate
        tests:
          - accepted_values:
              values: ['on_track', 'needs_support', 'at_risk']
      
      - name: is_activated
        description: Boolean flag indicating if student has completed first lesson
        tests:
          - not_null
      
      - name: mastery_rate
        description: Percentage of units mastered
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
              inclusive: true
      
      - name: days_active_last_7
        description: Days active in last 7 days (for DAU/WAU tracking)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 7
              inclusive: true

  - name: mart_user_avg_duration_monthly
    description: |
      Data mart that calculates the average duration between first and last event in the fact table,
      aggregated by month and year. Shows the average time between activity for all users.
      One row per month/year combination.
    columns:
      - name: year
        description: Year of the activity
        tests:
          - not_null

      - name: month
        description: Month number (1-12)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 12
              inclusive: true

      - name: month_name
        description: Name of the month
        tests:
          - not_null

      - name: avg_duration_seconds
        description: Average duration in seconds between first and last event per user in the month
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: avg_duration_minutes
        description: Average duration in minutes between first and last event per user in the month
        tests:
          - not_null

      - name: avg_duration_hours
        description: Average duration in hours between first and last event per user in the month
        tests:
          - not_null

      - name: avg_duration_days
        description: Average duration in days between first and last event per user in the month
        tests:
          - not_null

      - name: total_users
        description: Total number of users with activity in the month
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              inclusive: true

      - name: min_duration_seconds
        description: Minimum duration in seconds among all users in the month
        tests:
          - not_null

      - name: max_duration_seconds
        description: Maximum duration in seconds among all users in the month
        tests:
          - not_null

  - name: mart_product_rank_by_event_frequency
    description: |
      Data mart that ranks products by their event frequency over the last 30 days
      and counts the number of unique schools that had events for each product.
      One row per product with ranking and school count metrics.
    columns:
      - name: product_name
        description: Name of the product (e.g., English Language Arts, Science)
        tests:
          - not_null

      - name: product_rank
        description: Rank of the product based on event frequency (1 = highest frequency)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              inclusive: true

      - name: total_schools
        description: Count of unique schools that had events for this product in the last 30 days
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true